services:
  app:
    image: ui
    build:
      context: .
      dockerfile: Dockerfile
    command: uv run --frozen --no-dev marimo run src/main.py --host 0.0.0.0 --port 8000 --session-ttl=0
    environment:
      - LOG_LEVEL=INFO
    ports:
      - 3000:8000
